#!/bin/sh

# Check for stylus
if ! command -v stylua >/dev/null; then
  echo "Error: stylua is not installed"
  exit 1
fi

echo "Running lint check..."
make lint
if [ $? -ne 0 ]; then
 echo "Lint check failed, aborting commit."
 exit 1
fi

echo "Running format check..."
make format-check
if [ $? -ne 0 ]; then
 echo "Format check failed, aborting commit."
 exit 1
fi

exit 0
