"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "antonk52"
email = "halloy52@gmail.com"

[ui]
default-command = "log"

[aliases]
amend = ["squash"]
c = ["commit"]
ci = ["commit", "--interactive"]
cm = ["commit", "-m"]
d = ["diff", "--ignore-all-space"]
dg = ["diff", "--ignore-all-space", "--git"]
logr = ["log", "-r=all()"]
go = ["edit", "--ignore-immutable"]
h = ["-h"]
hide = ["abandon"]
s = ["status"]

[colors]
timestamp = "bright black"
"working_copy" = { bold = false }
"working_copy timestamp" = "bright black"

[git]
# when available fetch from upstream too, default is only from origin
# see https://jj-vcs.github.io/jj/latest/github/#using-several-remotes
fetch = ["upstream", "origin"]
