#!/bin/bash

# vim goodness
alias :sp='test -n "$TMUX" && tmux split-window'
alias :vs='test -n "$TMUX" && tmux split-window -h'
alias :q='exit'

# ls
if command -v eza &> /dev/null;
then
    alias ls='eza --color=never'
fi
alias ll='ls -alF'

alias cl='clear'

# dir manipulation
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias compare='diff -rq'
alias cdf='cd "$(fd --type d --exclude node_modules | fzf)"'
alias cdF='cd "$(fd --type d --no-ignore --exclude node_modules | fzf)"'

# git
alias g='git'
alias it='git' # fat fitngers
alias ga='git add'
alias gap='git add -p'
alias gs='git status -s'
alias gc='git commit -m'

# tmux aliases
alias tst='tmux start-server'
alias tks='tmux kill-server'
alias tl='tmux list-sessions'
alias ta='tm'

# attach to existing or start a named session by providing a name
# or a blank session by calling `tm`
tm() {
    if [ $# -eq 0 ]; then
        # No arguments provided; start tmux normally
        tmux
    else
        local session_name="$1"

        # Check if the session already exists
        if tmux has-session -t "$session_name" 2>/dev/null; then
            # Session exists; attach to it
            tmux attach-session -t "$session_name"
        else
            # Session does not exist; create a new one
            tmux new-session -s "$session_name"
        fi
    fi
}

# other aliases
alias e='exit'
alias o='open'
alias ax='chmod a+x'
alias h='eval $(history | fzf +s --tac --tiebreak=index | sed "s/ *[0-9]* *//")'
alias q='quit'
alias docker_stop_all='docker stop "$(docker ps -q)"'

export NOTES_PATH="$HOME"/Documents/notes
alias notes="cd $NOTES_PATH && $EDITOR -c NotesStart && cd -"

alias nnvim="~/Downloads/nvim-nightly/bin/nvim"

function _download_nvim_impl() {
    local name=$1
    local version=$2

    local old_pwd=$(pwd)
    cd ~/Downloads
    # clean up if it exists already
    rm -rf ./nvim-macos-arm64.tar.gz ./nvim-macos-arm64 ./"$name"
    # download tar with build
    wget --quiet https://github.com/neovim/neovim/releases/download/"$version"/nvim-macos-arm64.tar.gz && echo "- Downloaded"
    # to avoid "unknown developer" warning
    xattr -c ./nvim-macos-arm64.tar.gz > /dev/null 2>&1 && echo "- Removed attributes"
    # extract
    tar xzvf nvim-macos-arm64.tar.gz > /dev/null 2>&1 && echo "- Extracted"
    mv nvim-macos-arm64 "$name"
    ~/Downloads/"$name"/bin/nvim --version | grep 'NVIM v'
    # print archive date
    echo "Build from: $(ls -l ~/Downloads/nvim-macos-arm64.tar.gz | awk '{print $6, $7, $8}')"
    cd $old_pwd
}

alias get_nvim_nightly="_download_nvim_impl nvim-nightly nightly"
alias get_nvim="_download_nvim_impl nvim v0.10.4"
