name: default

on: [push, pull_request]

jobs:
  stylua:
    name: stylua
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: JohnnyMorganz/stylua-action@1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # CLI arguments
          args: --color always --check .

  luacheck:
    name: luacheck
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: nebularg/actions-luacheck@v1
        with:
          files:
            - wezterm
            - nvim
